dist: bionic # because using py>=3.7
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  # - "nightly"  # nightly build
install:
  - pip install -e .
  - pip install Pygments mock sphinx sphinx-rtd-theme recommonmark # just to build docs
  - pip install -r docs/requirements.txt # just to build docs
script:
  - which vro-diff # test if ready to be used
  # test help
  - vro-diff --help
  # Diff + legend
  - vro-diff ./tests/data/package_v1.0.package ./tests/data/package_v1.1.package --legend
  # Error case using --test
  - vro-diff --test tests/data/package_v1.0.package tests/data/package_v1.1.package || if [[ $? -eq 3 ]]; then true; fi
  # Test building docs
  - cd docs/ && make html