sudo: false
dist: xenial
language: python
matrix:
  include:
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: bionic
  - python: 3.8-dev
    dist: bionic
  - name: "Python 3.7 on Windows"
    os: windows     # Windows 10.0.17134 N/A Build 17134
    language: shell # 'language: python' is an error on Travis CI Windows
    before_install:
      - choco install python
      - python -m pip install --upgrade pip
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  - name: "Python 3.7 on macOS"
    os: osx
    osx_image: xcode10.2 # Python 3.7.2 running on macOS 10.14.3
    language: shell      # 'language: python' is an error on Travis CI macOS
install:
- pip install Pygments mock sphinx sphinx-rtd-theme recommonmark
- pip install -U -r docs/requirements.txt
- pip install .
script:
- which vro-diff
- vro-diff --help
- vro-diff --legend $TRAVIS_BUILD_DIR/tests/data/package_v1.0.package $TRAVIS_BUILD_DIR/tests/data/package_v1.1.package
- vro-diff --test $TRAVIS_BUILD_DIR/data/package_v1.0.package $TRAVIS_BUILD_DIR/tests/data/package_v1.1.package || if [[ $? -eq 3 ]]; then true; fi
- cd docs/ && make html
before_deploy: cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: lrivallain
  password:
    secure: dVDSBK6H1BrR/CzhYIAlUOXqIZ5B2MiaSbfGGRxXs9/U2oObqbEY1OwkWu1A+cVuAs0qd6wRW6O3GoL0azr2A4k0Dppd+LBYLXMyrVNIgWdgRrThJMBLDpFthNXNxGz9ykUsW9cXLvQg01c8Lnh/wh/qUZWA9P6DOIMpusiIcVASoauaHPfcqzWQbxIh6fdkm5XX3V/9PbOmliaMiqZJAx02AwxfP5Un/iGedZY7aqxOY1p/eTCytwDzV6oCZmGlYqY4Wrm+sEgmNSjlfUFQYWdjLfzONIkM/Woa6ZoVsVGYsoVGrTSA8uSFyvBSTMDSFsPgD2sfJKh1MP2fj3s0Sy4TZF6FbE6J+aNwQBaKFZ/emGluJSw6+XLT3hNSULJtHpilD30sinxF3EomJ8MJxz6Kzthvp/gsFhHDQvtdT3hcDJNTs0B1W0gdoTPAcvdA4EsYfhBJGwr1t7FtH2gDqpu1PKYF4qRfl3TJWc86hKInpfv6HZ2C7+3/3u2Q5maM6a9TKXB6bJFRM+OSFUgtenEgHgi0FrnK0Xt9dD9vpG2bV+oa9+7gAzvnDzGB0BECHDlXEQS0K0hO2UyRVYQJpHL58GGecT9ZMS996V6cuqFc2GRChzdgVDMfA+QgT81yz8aOWM+w4oJq7y/Mcy0Tk0kb+nLxJJNN+65AxlNe4gA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.7
