name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Check endpoint
      run: |
        which vro-diff
    - name: Check help
      run: |
        vro-diff --help
    - name: Run diff tests
      run: |
        vro-diff --legend ./tests/data/package_v1.0.package ./tests/data/package_v1.1.package
        vro-diff --test   ./tests/data/package_v1.0.package ./tests/data/package_v1.1.package || if [[ $? -eq 3 ]]; then true; else false; fi
